#!/bin/sh

exec /bin/dumb-init /bin/gosu consul /bin/consul lock -http-addr=$CONSUL_SERVER -n=1 lock/elb-consul/$AWS_REGION/$ELB_NAME /bin/consul watch -http-addr=$CONSUL_SERVER -type=service -service=$CONSUL_SERVICE /usr/local/bin/handler.py
